# File: backend/app/schemas/chatbot.py
from pydantic import BaseModel, ConfigDict
from datetime import datetime


from typing import Optional # Optional might be needed for update schemas later
import enum

class ChatbotStatus(str, enum.Enum): # Use str mixin for better JSON serialization
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"


# --- Base Schema ---
# Contains common fields shared between creation and reading.
class ChatbotBase(BaseModel):
    name: str
    # Add other non-sensitive fields here if needed in the future
    # description: Optional[str] = None

# --- Create Schema ---
# Inherits from Base, used specifically for creating a new chatbot via the API.
# Only includes fields the user needs to provide during creation.
class ChatbotCreate(ChatbotBase):
    # We don't ask for owner_id here; we'll get it from the authenticated user later.
    # We don't ask for created_at; the database sets it.
    pass # No additional fields needed beyond ChatbotBase for now

# --- Update Schema --- (We'll use this later)
# class ChatbotUpdate(ChatbotBase):
#     name: Optional[str] = None # Make fields optional for partial updates
#     # ... other updatable fields

# --- Read Schema (Response Model) ---
# Inherits from Base, used for returning chatbot data via the API.
# Includes fields generated by the database (id, created_at, owner_id).
class ChatbotRead(ChatbotBase):
    id: int
    owner_id: int
    status: ChatbotStatus
    created_at: datetime
    updated_at: Optional[datetime] = None

    # Pydantic V2 config for ORM mode
    model_config = ConfigDict(from_attributes=True)